# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9a0cc74343e778f7aaa2146c52f521c34861cbcc54fcaf8cc1eabd1ea75d001a7ea1fdbc8625eebc2449a2795e380ac88866a828200aeb414c36cf801369939

test:
  secret_key_base: 858ad6321bd94fee0584598beee6f7d2dca30d2a6e2cb54aeffe3f8cd6345de9abb3dba344e6a3fdbe1887006dda4dff0dc85f4058e330696a6091c773530a24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
